#ifndef _ECOL_MACRO_TEMPLATES_H_
#define _ECOL_MACRO_TEMPLATES_H_

#include "macro_templates_functions.h"

#define DECLARE_TEMPLATE_FUNCTION(MT_RETURN_TYPE, MT_FUNCTION_NAME, MT_FUNCTION_BODY, MT_TEMPLATE_TYPES, ...) \
    DECLARE_TEMPLATE_FUNCTION_CALL_N(MT_RETURN_TYPE, MT_FUNCTION_NAME, MT_FUNCTION_BODY, MT_TEMPLATE_TYPES, __VA_ARGS__)

#endif